codecov:
  ignore:
    - "cmd/graphql.ethereum/tools.go"
    - "cmd/graphql.ethereum/graph/generated.go"
    - "cmd/graphql.ethereum/graph/resolver.go"
    - "cmd/graphql.ethereum/graph/mocked.go"
    - "cmd/graphql.ethereum/graph/model/models_gen.go"
