
FROM rustlang/rust:nightly-bullseye-slim

RUN mkdir -p /usr/local/src/superposition/app.superposition.so

WORKDIR /usr/local/src/superposition/app.superposition.so

RUN apt-get update && apt-get install -y build-essential

RUN rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

COPY . .

RUN make contract
