[package]
name = "seawater"
version = "0.1.0"
edition = "2021"

[dependencies]
stylus-sdk.workspace = true
thiserror.workspace = true
tiny-keccak.workspace = true
wee_alloc.workspace = true

[features]
export-abi = ["stylus-sdk/export-abi"]
