import { Pool } from "@/app/stake/_MyPositionsTable/columns";

export const mockMyPositions: Pool[] = [
  {
    id: "1",
    positionId: 0,
    tokens: [
      {
        address: "0x0",
        name: "USDC",
        symbol: "USDC",
        decimals: 6,
        icon: "/icons/usd-coin-usdc-logo.svg",
      },
      {
        address: "0x0",
        name: "ETH",
        symbol: "ETH",
        decimals: 18,
        icon: "/ethereum-eth-logo.svg",
      },
    ],
    duration: 100,
    staked: 100,
    totalYield: 100,
  },
  {
    id: "2",
    positionId: 0,
    tokens: [
      {
        address: "0x0",
        name: "USDT",
        symbol: "USDT",
        decimals: 6,
        icon: "/icons/usd-coin-usdc-logo.svg",
      },
      {
        address: "0x0",
        name: "ETH",
        symbol: "ETH",
        decimals: 18,
        icon: "/ethereum-eth-logo.svg",
      },
    ],
    duration: 100,
    staked: 100,
    totalYield: 100,
  },
  {
    id: "3",
    positionId: 0,
    tokens: [
      {
        address: "0x0",
        name: "USDC",
        symbol: "USDC",
        decimals: 6,
        icon: "/icons/usd-coin-usdc-logo.svg",
      },
      {
        address: "0x0",
        name: "USDT",
        symbol: "USDT",
        decimals: 6,
        icon: "/icons/usd-coin-usdc-logo.svg",
      },
    ],
    duration: 100,
    staked: 100,
    totalYield: 100,
  },
  {
    id: "4",
    positionId: 0,
    tokens: [
      {
        address: "0x0",
        name: "USDC",
        symbol: "USDC",
        decimals: 6,
        icon: "/icons/usd-coin-usdc-logo.svg",
      },
      {
        address: "0x0",
        name: "ETH",
        symbol: "ETH",
        decimals: 18,
        icon: "/ethereum-eth-logo.svg",
      },
    ],
    duration: 100,
    staked: 100,
    totalYield: 100,
  },
  {
    id: "5",
    positionId: 0,
    tokens: [
      {
        address: "0x0",
        name: "USDT",
        symbol: "USDT",
        decimals: 6,
        icon: "/icons/usd-coin-usdc-logo.svg",
      },
      {
        address: "0x0",
        name: "ETH",
        symbol: "ETH",
        decimals: 18,
        icon: "/ethereum-eth-logo.svg",
      },
    ],
    duration: 100,
    staked: 100,
    totalYield: 100,
  },
  {
    id: "6",
    positionId: 0,
    tokens: [
      {
        address: "0x0",
        name: "USDC",
        symbol: "USDC",
        decimals: 6,
        icon: "/icons/usd-coin-usdc-logo.svg",
      },
      {
        address: "0x0",
        name: "USDT",
        symbol: "USDT",
        decimals: 6,
        icon: "/icons/usd-coin-usdc-logo.svg",
      },
    ],
    duration: 100,
    staked: 100,
    totalYield: 100,
  },
  {
    id: "7",
    positionId: 0,
    tokens: [
      {
        address: "0x0",
        name: "USDC",
        symbol: "USDC",
        decimals: 6,
        icon: "/icons/usd-coin-usdc-logo.svg",
      },
      {
        address: "0x0",
        name: "ETH",
        symbol: "ETH",
        decimals: 18,
        icon: "/ethereum-eth-logo.svg",
      },
    ],
    duration: 100,
    staked: 100,
    totalYield: 100,
  },
  {
    id: "8",
    positionId: 0,
    tokens: [
      {
        address: "0x0",
        name: "USDT",
        symbol: "USDT",
        decimals: 6,
        icon: "/icons/usd-coin-usdc-logo.svg",
      },
      {
        address: "0x0",
        name: "ETH",
        symbol: "ETH",
        decimals: 18,
        icon: "/ethereum-eth-logo.svg",
      },
    ],
    duration: 100,
    staked: 100,
    totalYield: 100,
  },
  {
    id: "9",
    positionId: 0,
    tokens: [
      {
        address: "0x0",
        name: "USDC",
        symbol: "USDC",
        decimals: 6,
        icon: "/icons/usd-coin-usdc-logo.svg",
      },
      {
        address: "0x0",
        name: "USDT",
        symbol: "USDT",
        decimals: 6,
        icon: "/icons/usd-coin-usdc-logo.svg",
      },
    ],
    duration: 100,
    staked: 100,
    totalYield: 100,
  },
];
