// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LiquidityOverTime struct {
	Daily   []PairAmount `json:"daily"`
	Monthly []PairAmount `json:"monthly"`
}

type Mutation struct {
}

type PairAmount struct {
	Timestamp int    `json:"timestamp"`
	Fusdc     Amount `json:"fusdc"`
	Token1    Amount `json:"token1"`
}

type PriceOverTime struct {
	Daily   []string `json:"daily"`
	Monthly []string `json:"monthly"`
}

type Query struct {
}

type Token struct {
	Address     string `json:"address"`
	Name        string `json:"name"`
	TotalSupply string `json:"totalSupply"`
	Decimals    int    `json:"decimals"`
	Symbol      string `json:"symbol"`
}

type TokenBalance struct {
	Token   Token  `json:"token"`
	Balance Amount `json:"balance"`
}

type UtilityIncentive struct {
	AmountGivenOut string `json:"amountGivenOut"`
	MaximumAmount  string `json:"maximumAmount"`
}

type VolumeOverTime struct {
	Daily   []PairAmount `json:"daily"`
	Monthly []PairAmount `json:"monthly"`
}

type YieldOverTime struct {
	Daily   []PairAmount `json:"daily"`
	Monthly []PairAmount `json:"monthly"`
}
