// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type SeawaterAmount struct {
	Token       Token   `json:"token"`
	Value       string  `json:"value"`
	ValueScaled string  `json:"valueScaled"`
	ValueUsd    *string `json:"valueUsd,omitempty"`
}

type SeawaterPool struct {
	Address string `json:"address"`
	ApyUsd  string `json:"apyUsd"`
}

type SeawaterPosition struct {
	ID    string `json:"id"`
	Owner Wallet `json:"owner"`
}

type SeawaterSwap1 struct {
	User       Wallet         `json:"user"`
	Pool       SeawaterPool   `json:"pool"`
	ZeroForOne bool           `json:"zeroForOne"`
	Amount0    SeawaterAmount `json:"amount0"`
	Amount1    SeawaterAmount `json:"amount1"`
	FinalTick  string         `json:"finalTick"`
}
