[package]
name = "erc1155-token"
version = "0.1.0"
edition = "2021"

[dependencies]
stylus-sdk = "0.2.4"
thiserror = "1.0.48"
tiny-keccak = "2.0.2"
wee_alloc = "0.4.5"

[features]
export-abi = ["stylus-sdk/export-abi"]
