import "./globals.css";
import type { Metadata } from "next";
import Web3ModalProvider from "@/context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function Provider({ children }: { children: React.ReactNode }) {
  return <Web3ModalProvider>{children}</Web3ModalProvider>;
}
