[workspace]

resolver = "2"

members = [
    "seawater",
    "leo",
]

[profile.dev]
opt-level = "s"
debug = true
debug-assertions = true
panic = "unwind"
codegen-units = 1

[profile.release]
codegen-units = 1
panic = "abort"
strip = true
lto = true
debug = false
rpath = false
debug-assertions = false
incremental = false

[profile.release-complete]
opt-level = 3
inherits = "release"

[profile.release-codesize]
opt-level = "z"
inherits = "release"

[workspace.dependencies]
stylus-sdk = "0.7.0"
stylus-proc = "0.7.0"
tiny-keccak = "2.0.2"
ruint = { version = "1.11.0", features = ["num-traits"], default-features = false }
num-traits = { version = "0.2.19", default-features = false }
alloy-primitives = { version = "=0.8.14", default-features = false, features = ["native-keccak"] }
alloy-sol-types = { version = "=0.8.14", default-features = false }
alloy-sol-macro = { version = "=0.8.14", default-features = false }
ruint-macro = "1.2.1"
keccak-const = "0.2.0"
const-hex = { version = "1.10.0", features = ["alloc"], default-features = false }
