name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - development
#    paths:
#      - 'features/**'
#      - 'static/**'
#      - 'audits/**'
  pull_request:
    branches:
      - development
#    paths:
#      - 'features/**'
#      - 'static/**'
#      - 'audits/**'

jobs:
  deploy-features:
#    if: contains(github.event.head_commit.message, 'features/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_TOKEN }}
          # update
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # update
          projectName: ${{ secrets.CLOUDFLARE_FEATURES_PROJECT_NAME }}
          directory: .
          # to enable Github Deployments
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          workingDirectory: features
#
#  deploy-static:
##    if: contains(github.event.head_commit.message, 'static/')
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Install Wrangler
#        run: npm install -g wrangler
#
#      - name: Deploy to Cloudflare Pages (static)
#        env:
#          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
#          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
#          CLOUDFLARE_APP_PROJECT_NAME: ${{ secrets.CLOUDFLARE_APP_PROJECT_NAME_STATIC }}
#        run: |
#          wrangler pages deploy ./static --project-name $CLOUDFLARE_APP_PROJECT_NAME
#
#  deploy-audits:
##    if: contains(github.event.head_commit.message, 'audits/')
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Install Wrangler
#        run: npm install -g wrangler
#
#      - name: Deploy to Cloudflare Pages (audits)
#        env:
#          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
#          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
#          CLOUDFLARE_APP_PROJECT_NAME: ${{ secrets.CLOUDFLARE_APP_PROJECT_NAME_AUDITS }}
#        run: |
#          wrangler pages deploy ./audits --project-name $CLOUDFLARE_APP_PROJECT_NAME
