name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
    paths:
      - 'features/**'
      - 'static/**'
      - 'audits/**'
  pull_request:
    branches:
      - main
    paths:
      - 'features/**'
      - 'static/**'
      - 'audits/**'

jobs:
  deploy-features:
    if: contains(github.event.head_commit.message, 'features/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd features
          npm install

      - name: Build project
        run: |
          cd features
          npm run build

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_PROJECT_NAME: 'features'
        run: |
          npx @cloudflare/wrangler pages publish ./features/build --project-name $CLOUDFLARE_PROJECT_NAME

  deploy-static:
    if: contains(github.event.head_commit.message, 'static/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd static
          npm install

      - name: Build project
        run: |
          cd static
          npm run build

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_PROJECT_NAME: 'static'
        run: |
          npx @cloudflare/wrangler pages publish ./static/build --project-name $CLOUDFLARE_PROJECT_NAME

  deploy-audits:
    if: contains(github.event.head_commit.message, 'audits/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd audits
          npm install

      - name: Build project
        run: |
          cd audits
          npm run build

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_PROJECT_NAME: 'audits'
        run: |
          npx @cloudflare/wrangler pages publish ./audits/build --project-name $CLOUDFLARE_PROJECT_NAME
