name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - development
#    paths:
#      - 'features/**'
#      - 'static/**'
#      - 'audits/**'
  pull_request:
    branches:
      - development
#    paths:
#      - 'features/**'
#      - 'static/**'
#      - 'audits/**'

jobs:
  deploy-features:
#    if: contains(github.event.head_commit.message, 'features/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_FEATURES_PROJECT_NAME }}
          directory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          workingDirectory: features

  deploy-static:
#    if: contains(github.event.head_commit.message, 'static/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_STATIC_PROJECT_NAME }}
          directory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          workingDirectory: static

  deploy-audit:
#    if: contains(github.event.head_commit.message, 'audit/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_AUDITS_PROJECT_NAME }}
          directory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          workingDirectory: audit
