name: Deploy Lambda

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.1'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Build lambda zip
        run: |
          cd cmd/graphql.ethereum
          make lambda

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2
        run: |
          aws lambda update-function-code --function-name graphql-ethereum \
          --zip-file fileb://cmd/graphql.ethereum/bootstrap.zip
