name: Deploy audits

on:
  push:
    branches:
      - development
    paths:
      - 'audits/**'
  pull_request:
    branches:
      - development
    paths:
      - 'audits/**'

jobs:
  deploy-audits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: 'true'

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_AUDITS_PROJECT_NAME }}
          directory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          workingDirectory: audits
