name: frontend-tests

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
jobs:
  frontend-tests:
    name: Run Frontend Tests
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.changed_files, 'web/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Node dependencies
        run: |
          cd web
          npm install

      - name: Run Jest tests
        run: |
          cd web
          npm run test:jest

      - name: Run Cypress tests
        run: |
          cd web
          npm run test:cypress
