name: Snyk Vulnerability Scan

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  snyk-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.3'  # Specify the Go version you need

      - name: Install Go dependencies
        run: go mod tidy

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        with:
          args: test --org=$SNYK_ORG --severity-threshold=high
        env:
          SNYK_ORG: ${{ secrets.SNYK_ORG }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk to monitor project
        uses: snyk/actions/golang@master
        with:
          args: monitor --org=your-org-name  # Adjust the org as needed
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
