name: Jest Unit Tests

on:
  push:
    branches: 
      - development
    paths: 
      - 'web/**'
      - '.github/workflows/tests-unit-js.yml'
  pull_request:
    branches: 
      - development

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './web'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.15.0

      - name: Enable pnpm
        run: corepack enable pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Jest tests
        run: pnpm test:unit

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jest-coverage
          path: web/jest-coverage/
          retention-days: 30
          
      - name: Upload coverage reports to Codecov
        if: ${{ !startsWith(github.ref_name, 'dependabot') }}
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          flags: unittests 
          name: js-unit-tests
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true 
