name: Playwright E2E Tests

on:
  push:
    branches:
      - development
      - test-suite-js
    paths: 
      - 'web/**'
      - 'web/tests-e2e.yml'
  pull_request:
    branches:
      - development
      - test-suite-js

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Enable pnpm
        run: corepack enable pnpm
      - name: Change directory to web
        run: cd web
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-coverage
          path: playwright-coverage/
          retention-days: 30
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true 
          flags: e2e
          name: e2e-tests 
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true 
